---
- hosts: slave1
  become: yes
  name: Installing apache2 on slave1
  tasks:
  - name: Install apache2
    apt:  
        update_cache: yes
        name: apache2 
        state: latest
- hosts: slave2
  become: yes
  name: Installing nginx on slave2
  tasks:
  - name: installing nginx
    apt: 
      name=nginx 
      state=latest
